name: code_merger_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.0
  path: ^1.8.0
  clipboard: ^0.1.3
  lottie: ^1.2.1
  google_mobile_ads: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.7.0

flutter:
  uses-material-design: true


msix_config:
  display_name: Code Merger
  publisher_display_name: NersNote
  identity_name: com.nersnote.codemerger
  msix_version: 1.0.0.0
  logo_path: C:\path\to\your\logo.png
  capabilities: internetClient
